GREENHOUSE_COMPANIES = {
    "OpenAI": "openai",
    "Stripe": "stripe",
    "Datadog": "datadog",
    "Coinbase": "coinbase",
    "Plaid": "plaid",
    "Vercel": "vercel",
    "Notion": "notion",
    "Canva": "canva",
    "Figma": "figma",
    "Ramp": "ramp",
    "HashiCorp": "hashicorp",
    "Cloudflare": "cloudflare",
    "Snyk": "snyk",
    "Cockroach Labs": "cockroachlabs",
    "Confluent": "confluent",
    "ClickHouse": "clickhouse",
    "Scale AI": "scaleai",
    "Elastic": "elastic",
    "MongoDB": "mongodb",
    "GitLab": "gitlab"
}

LEVER_COMPANIES = {
    "Netflix": "netflix",
    "Discord": "discord",
    "Brex": "brex",
    "Miro": "miro",
    "Rippling": "rippling",
    "Zapier": "zapier",
    "Calm": "calm",
    "Faire": "faire",
    "PostHog": "posthog",
    "Render": "render",
    "Sentry": "sentry",
    "Vanta": "vanta",
    "Amplitude": "amplitude",
    "Abnormal AI": "abnormalsecurity",
    "Samsara": "samsara",
    "Glean": "gleanwork",
    "Retool": "retool",
    "Cockroach Labs": "cockroachlabs",
    "Lattice": "lattice",
    "Gusto": "gusto"
}